
FROM node:8 AS static_builder

WORKDIR /supply_chain/manufacturer_client
COPY manufacturer_client/package.json .
RUN npm install

COPY protos/ ../protos/
COPY manufacturer_client/ .
RUN npm run build

FROM httpd:2.4

COPY --from=static_builder /supply_chain/manufacturer_client/public/ /usr/local/apache2/htdocs/

RUN echo "\
\n\
ServerName manufacturer_client\n\
AddDefaultCharset utf-8\n\
LoadModule proxy_module modules/mod_proxy.so\n\
LoadModule proxy_http_module modules/mod_proxy_http.so\n\
ProxyPass /api http://server:3000\n\
ProxyPassReverse /api http://server:3000\n\
\n\
" >>/usr/local/apache2/conf/httpd.conf

EXPOSE 80/tcp
